CREATE TABLE USUARIO(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	NOME_USUARIO VARCHAR(25) NOT NULL,
	SENHA VARCHAR(32) NOT NULL
);

CREATE TABLE BEBIDA(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	MARCA VARCHAR(50) NOT NULL,
	SABOR VARCHAR(50) NOT NULL,
	VOLUME VARCHAR(50) NOT NULL,
	PRECO DOUBLE NOT NULL
);

CREATE TABLE PIZZA(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	INGREDIENTES VARCHAR(500) NOT NULL,
	PRECO_P DOUBLE NOT NULL,
	PRECO_M DOUBLE NOT NULL,
	PRECO_G DOUBLE NOT NULL,
	PRECO_GG DOUBLE NOT NULL
);

CREATE TABLE CLIENTE(
	ID INTEGER NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	RG VARCHAR(10) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR NOT NULL,
	TELEFONE VARCHAR(13) NOT NULL,
	ENDERECO VARCHAR(300) NOT NULL	
);

CREATE TABLE PEDIDO_VENDA(
	ID INTEGER PRIMARY KEY IDENTITY NOT NULL,
	DATA DATE,
	VALOR_TOTAL DOUBLE,
	USUARIO INTEGER,
	CLIENTE INTEGER DEFAULT -1	
);

CREATE TABLE ITENS_PEDIDO_VENDA(
	ID INT NOT NULL,
	VALORUNITARIO DOUBLE NOT NULL,
	VALORTOTAL DOUBLE NOT NULL,
	VENDA INTEGER NOT NULL,
	FOREIGN KEY(VENDA) REFERENCES VENDA(CODIGO)
);


CREATE TABLE CONTA(
	CODIGO INTEGER IDENTITY NOT NULL,
	STATUS BOOLEAN DEFAULT TRUE,
	VALORTOTAL DOUBLE NOT NULL,
	DATA DATE DEFAULT CURRENT_DATE,
	VENDA INTEGER NOT NULL,
	FOREIGN KEY(VENDA) REFERENCES VENDA(CODIGO)
);

CREATE TABLE CAIXADIARIO(
	CODIGO INTEGER IDENTITY NOT NULL,
	DATA DATE DEFAULT CURRENT_DATE,
	STATUS BOOLEAN DEFAULT TRUE,
	VALOR_INICIAL DOUBLE DEFAULT 0.0,
	VALOR_FINAL DOUBLE
);

CREATE TABLE LIQUIDACAO(
	CONTA INTEGER NOT NULL,
	CAIXADIARIO INTEGER NOT NULL,
	VALORPAGO DOUBLE NOT NULL,
	FOREIGN KEY (CONTA) REFERENCES CONTA(CODIGO),
	FOREIGN KEY (CAIXADIARIO) REFERENCES CAIXADIARIO(CODIGO)
);