/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestao.pizzaria.apresentacao;

import br.com.gestao.pizzaria.entidade.Pizza;
import br.com.gestao.pizzaria.excecao.CampoObrigatorioException;
import br.com.gestao.pizzaria.excecao.GestaoPizzariaException;
import br.com.gestao.pizzaria.negocio.PizzaBO;
import javax.swing.JOptionPane;

/**
 *
 * @author melot_000
 */
public class CadastrarPizzaForm extends javax.swing.JFrame {

    private PesquisarPizzaForm pesquisarPizzaForm;
    private Pizza pizza;

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarPizzaForm() {
        this.pizza = new Pizza();
        initComponents();
    }

    public CadastrarPizzaForm(PesquisarPizzaForm pesquisarPizzaForm, Pizza pizzaParaEdicao) {
        this.pesquisarPizzaForm = pesquisarPizzaForm;

        this.pizza = pizzaParaEdicao;
        initComponents();
        this.inicializarCamposTela();

    }

    private void inicializarCamposTela() {
        txtNome.setText(pizza.getNome());
        txtIngredientes.setText(pizza.getIngredientes());
        
        String preco = Double.toString(pizza.getPrecoPequena());
        txtPrecoPequena.setText(preco);
        
        preco = Double.toString(pizza.getPrecoMedia());
        txtPrecoMedia.setText(preco);
        
        preco = Double.toString(pizza.getPrecoGrande());
        txtPrecoGrande.setText(preco);
        
        preco = Double.toString(pizza.getPrecoGigante());
        txtPrecoGigante.setText(preco);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroDePizza = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSabor = new javax.swing.JLabel();
        lblCampoObrigatorio = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        txtPrecoPequena = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredientes = new javax.swing.JTextArea();
        lblP = new javax.swing.JLabel();
        txtPrecoMedia = new javax.swing.JFormattedTextField();
        lblM = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        txtPrecoGrande = new javax.swing.JFormattedTextField();
        lblGG = new javax.swing.JLabel();
        txtPrecoGigante = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pizza");
        setExtendedState(6);

        pnlCadastroDePizza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Pizzas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("*Nome:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSabor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSabor.setText("*Ingredientes:");

        lblCampoObrigatorio.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblCampoObrigatorio.setText("Campos com (*) são obrigtórios.");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/diskette18.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/clear5.png"))); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPreco.setText("*PREÇOS R$:");

        txtPrecoPequena.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecoPequena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecoPequena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtIngredientes.setColumns(20);
        txtIngredientes.setRows(5);
        jScrollPane1.setViewportView(txtIngredientes);

        lblP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblP.setText("P:");

        txtPrecoMedia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecoMedia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecoMedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblM.setText("M:");

        lblG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblG.setText("G:");

        txtPrecoGrande.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecoGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecoGrande.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblGG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGG.setText("GG:");

        txtPrecoGigante.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecoGigante.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPrecoGigante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlCadastroDePizzaLayout = new javax.swing.GroupLayout(pnlCadastroDePizza);
        pnlCadastroDePizza.setLayout(pnlCadastroDePizzaLayout);
        pnlCadastroDePizzaLayout.setHorizontalGroup(
            pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                        .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(lblSabor)
                            .addComponent(lblCampoObrigatorio)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroDePizzaLayout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(365, 365, Short.MAX_VALUE))
                    .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                        .addComponent(lblGG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoGigante, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                        .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblP, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrecoPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPreco))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCadastroDePizzaLayout.setVerticalGroup(
            pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroDePizzaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCampoObrigatorio)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblP)
                    .addComponent(txtPrecoPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblG)
                    .addComponent(txtPrecoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoGigante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(pnlCadastroDePizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroDePizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCadastroDePizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCadastroDePizza.getAccessibleContext().setAccessibleName("Cadastro de pizzas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
       this.fecharCadastroPizza();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.salvarPizza();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPizzaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPizzaForm().setVisible(true);
            }
        });
    }

    private void salvarPizza() {
        try {
            this.validarCamposObrigatorios();
            this.recuperarCamposTela();

            PizzaBO pizzaBO = new PizzaBO();
            String tituloMensagem;

            if (pizza.getId() == -1) {
                tituloMensagem = "Cadastro de pizza";
                pizzaBO.inserir(pizza);
                JOptionPane.showMessageDialog(this, "Pizza cadastrada com sucesso!", tituloMensagem, JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                tituloMensagem = "Editar pizza";
                pizzaBO.alterar(pizza);
                JOptionPane.showMessageDialog(this, "Pizza alterada com sucesso!", tituloMensagem, JOptionPane.INFORMATION_MESSAGE);
                if (pesquisarPizzaForm == null) {
                    pesquisarPizzaForm = new PesquisarPizzaForm();
                }
                this.fecharCadastroPizza();
            }
            this.limparCamposTela();
        } catch (GestaoPizzariaException e) {
            String mensagem = "Erro ao realizar cadastro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de pizza", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de pizza", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparCamposTela() {
        txtNome.setText("");
        txtIngredientes.setText("");
        txtPrecoPequena.setText("");
        txtPrecoMedia.setText("");
        txtPrecoGrande.setText("");
        txtPrecoGigante.setText("");
    }

    private void recuperarCamposTela(){        
        pizza.setNome(txtNome.getText());
        pizza.setIngredientes(txtIngredientes.getText());
        
        String precoString = txtPrecoPequena.getText();
        precoString = precoString.replace(",", ".");
        double preco = Double.parseDouble(precoString);
        pizza.setPrecoPequena(preco);
        
        precoString = txtPrecoMedia.getText();
        precoString = precoString.replace(",", ".");
        preco = Double.parseDouble(precoString);
        pizza.setPrecoMedia(preco);
        
        precoString = txtPrecoGrande.getText();
        precoString = precoString.replace(",", ".");
        preco = Double.parseDouble(precoString);
        pizza.setPrecoGrande(preco);
        
        precoString = txtPrecoGigante.getText();
        precoString = precoString.replace(",", ".");
        preco = Double.parseDouble(precoString);
        pizza.setPrecoGigante(preco);       
    }

    private void validarCamposObrigatorios() {
        if (txtNome.getText().trim().isEmpty()
            || txtIngredientes.getText().trim().isEmpty()                
            || txtPrecoPequena.getText().trim().isEmpty()
            || txtPrecoMedia.getText().trim().isEmpty()
            || txtPrecoGrande.getText().trim().isEmpty()
            || txtPrecoGigante.getText().trim().isEmpty()) 
        {
            throw new CampoObrigatorioException();
        }
    }
    
    private void fecharCadastroPizza(){
        CadastrarPizzaForm.this.dispose();
        if (pesquisarPizzaForm == null) {
            pesquisarPizzaForm = new PesquisarPizzaForm();
        }
        pesquisarPizzaForm.setVisible(true);
        pesquisarPizzaForm.toFront();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCampoObrigatorio;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblGG;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblSabor;
    private javax.swing.JPanel pnlCadastroDePizza;
    private javax.swing.JTextArea txtIngredientes;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPrecoGigante;
    private javax.swing.JFormattedTextField txtPrecoGrande;
    private javax.swing.JFormattedTextField txtPrecoMedia;
    private javax.swing.JFormattedTextField txtPrecoPequena;
    // End of variables declaration//GEN-END:variables
}
