/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestao.pizzaria.apresentacao;

import br.com.gestao.pizzaria.entidade.Usuario;
import br.com.gestao.pizzaria.excecao.CampoObrigatorioException;
import br.com.gestao.pizzaria.excecao.GestaoPizzariaException;
import br.com.gestao.pizzaria.excecao.SenhasDiferentesException;
import br.com.gestao.pizzaria.negocio.UsuarioBO;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author melot_000
 */
public class CadastrarUsuarioForm extends javax.swing.JFrame {

    private PesquisarUsuarioForm pesquisarUsuarioForm;
    private Usuario usuario;

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuarioForm() {
        this.usuario = new Usuario();
        initComponents();
    }

    public CadastrarUsuarioForm(PesquisarUsuarioForm pesquisarUsuarioForm, Usuario UsuarioParaEdicao) {
        this.pesquisarUsuarioForm = pesquisarUsuarioForm;

        this.usuario = UsuarioParaEdicao;
        initComponents();
        this.inicializarCamposTela();

    }

    private void inicializarCamposTela() {
        txtNome.setText(usuario.getNome());
        txtNomeUsuario.setText(usuario.getNomeUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroDeUsuario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNomeUsuario = new javax.swing.JLabel();
        lblCampoObrigatorio = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblConfirmaSenha = new javax.swing.JLabel();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de usuários");
        setExtendedState(6);

        pnlCadastroDeUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de usuários", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("*Nome Completo:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeUsuario.setText("*Nome de usuário:");

        lblCampoObrigatorio.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblCampoObrigatorio.setText("Campos com (*) são obrigtórios.");

        txtNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("*Senha:");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/diskette18.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/clear5.png"))); // NOI18N
        btnFechar.setText("FECHAR");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblConfirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConfirmaSenha.setText("*Comfirma Senha:");

        javax.swing.GroupLayout pnlCadastroDeUsuarioLayout = new javax.swing.GroupLayout(pnlCadastroDeUsuario);
        pnlCadastroDeUsuario.setLayout(pnlCadastroDeUsuarioLayout);
        pnlCadastroDeUsuarioLayout.setHorizontalGroup(
            pnlCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroDeUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeUsuario)
                    .addComponent(lblConfirmaSenha)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(lblNomeUsuario)
                    .addComponent(lblCampoObrigatorio)
                    .addComponent(lblSenha)
                    .addGroup(pnlCadastroDeUsuarioLayout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtConfirmaSenha)
                    .addComponent(txtSenha))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        pnlCadastroDeUsuarioLayout.setVerticalGroup(
            pnlCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroDeUsuarioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCampoObrigatorio)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirmaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(pnlCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadastroDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCadastroDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCadastroDeUsuario.getAccessibleContext().setAccessibleName("Cadastro de usuarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
       this.fecharCadastroUsuario();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.salvarUsuario();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuarioForm().setVisible(true);
            }
        });
    }

    private void salvarUsuario() {
        try {
            this.validarCamposObrigatorios();
            this.recuperarCamposTela();

            UsuarioBO usuarioBO = new UsuarioBO();
            String tituloMensagem;

            if (usuario.getID() == -1) {
                tituloMensagem = "Cadastro de Usuário";
                usuarioBO.inserir(usuario);
                JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", tituloMensagem, JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                tituloMensagem = "Editar Usuário";
                usuarioBO.alterar(usuario);
                JOptionPane.showMessageDialog(this, "Usuario alterado com sucesso!", tituloMensagem, JOptionPane.INFORMATION_MESSAGE);
                if (pesquisarUsuarioForm == null) {
                    pesquisarUsuarioForm = new PesquisarUsuarioForm();
                }
                this.fecharCadastroUsuario();
            }
            this.limparCamposTela();
        } catch (GestaoPizzariaException e) {
            String mensagem = "Erro ao realizar cadastro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de usuário", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de usuário", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparCamposTela() {
        txtNome.setText("");
        txtNomeUsuario.setText("");
        txtSenha.setText("");
        txtConfirmaSenha.setText("");
    }

    private void recuperarCamposTela() throws NoSuchAlgorithmException, UnsupportedEncodingException{

        usuario.setNome(txtNome.getText());
        usuario.setNomeUsuario(txtNomeUsuario.getText());
        char[] chars = txtSenha.getPassword();  
        String senha = String.valueOf(chars);
            
        UsuarioBO usuarioBO = new UsuarioBO();
        String senhaCriptografada;
        senhaCriptografada = usuarioBO.criptografarSenha(senha);
        usuario.setSenha(senhaCriptografada);

    }

    private void validarCamposObrigatorios() {
        
        char[] chars = txtSenha.getPassword();  
        String senha = String.valueOf(chars);
        chars = txtConfirmaSenha.getPassword(); 
        String confirmaSenha = String.valueOf(chars);
           
        if (txtNome.getText().trim().isEmpty()
            || txtNomeUsuario.getText().trim().isEmpty()
            || senha.trim().isEmpty()
            || confirmaSenha.trim().isEmpty()) {
            throw new CampoObrigatorioException();
        }        
        compararCamposSenha(senha, confirmaSenha);
    }
    
    private void compararCamposSenha(String senha, String confirmaSenha){
        
        if (!senha.equals(confirmaSenha)){
            throw new SenhasDiferentesException();
        }    
    }
    
    private void fecharCadastroUsuario(){
        CadastrarUsuarioForm.this.dispose();
        if (pesquisarUsuarioForm == null) {
            pesquisarUsuarioForm = new PesquisarUsuarioForm();
        }
        pesquisarUsuarioForm.setVisible(true);
        pesquisarUsuarioForm.toFront();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCampoObrigatorio;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlCadastroDeUsuario;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
