/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestao.pizzaria.apresentacao;

/**
 *
 * @author melot_000
 */
public class TelaInicialSistema extends javax.swing.JFrame {

    PesquisarBebidaForm pesquisarBebidaForm;
    PesquisarUsuarioForm pesquisarUsuarioForm;
    PesquisarPizzaForm pesquisarPizzaForm;
    PesquisarClienteForm pesquisarClienteForm;
    PesquisarPedidoForm pesquisarPedidoForm;
    
    CadastrarBebidaForm cadastrarBebidaForm;
    CadastrarUsuarioForm cadastrarUsuarioForm;
    CadastrarPizzaForm cadastrarPizzaForm;
    CadastrarClienteForm cadastrarClienteForm;
    CadastrarPedidoForm cadastrarPedidoForm;

    /**
     * Creates new form TelaInicialSistema
     */
    public TelaInicialSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackground = new javax.swing.JLabel();
        mnuTelaPrincipal = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuNovoCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPesquisarCliente = new javax.swing.JMenuItem();
        mnuBebidas = new javax.swing.JMenu();
        mnuNovaBebida = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuPesquisarBebida = new javax.swing.JMenuItem();
        mnuPizzas = new javax.swing.JMenu();
        mnuNovaPizza = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuPesquisarPizza = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        mnuNovoPedido = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuPesquisarPedido = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuNovoUsuario = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuPesquisarUsuario = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuAjuda = new javax.swing.JMenu();
        mnuUsuariLogadoSistema = new javax.swing.JMenu();
        mnuMudarSenha = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestão Pizzaria");
        setExtendedState(6);

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/italian food11.png"))); // NOI18N
        lblBackground.setLabelFor(this);
        lblBackground.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBackground.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mnuTelaPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        mnuTelaPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        mnuTelaPrincipal.setAlignmentY(0.5F);
        mnuTelaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/user73.png"))); // NOI18N
        mnuClientes.setText("Clientes");
        mnuClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuClientes.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuClientes.setVerifyInputWhenFocusTarget(false);

        mnuNovoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/add14.png"))); // NOI18N
        mnuNovoCliente.setText("Novo");
        mnuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuNovoCliente);
        mnuClientes.add(jSeparator1);

        mnuPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/magnifying-glass11.png"))); // NOI18N
        mnuPesquisarCliente.setText("Pesquisar");
        mnuPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisarClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuPesquisarCliente);

        mnuTelaPrincipal.add(mnuClientes);
        mnuClientes.getAccessibleContext().setAccessibleName("");

        mnuBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/bottle24.png"))); // NOI18N
        mnuBebidas.setText("Bebidas");
        mnuBebidas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuBebidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuBebidas.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuBebidas.setVerifyInputWhenFocusTarget(false);

        mnuNovaBebida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuNovaBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/add204.png"))); // NOI18N
        mnuNovaBebida.setText("Nova");
        mnuNovaBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaBebidaActionPerformed(evt);
            }
        });
        mnuBebidas.add(mnuNovaBebida);
        mnuBebidas.add(jSeparator2);

        mnuPesquisarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/magnifying-glass11.png"))); // NOI18N
        mnuPesquisarBebida.setText("Pesquisar");
        mnuPesquisarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisarBebidaActionPerformed(evt);
            }
        });
        mnuBebidas.add(mnuPesquisarBebida);

        mnuTelaPrincipal.add(mnuBebidas);
        mnuBebidas.getAccessibleContext().setAccessibleName("");

        mnuPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/italian1.png"))); // NOI18N
        mnuPizzas.setText("Pizzas");
        mnuPizzas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuPizzas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuPizzas.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuPizzas.setVerifyInputWhenFocusTarget(false);

        mnuNovaPizza.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuNovaPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/add204.png"))); // NOI18N
        mnuNovaPizza.setText("Nova");
        mnuNovaPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaPizzaActionPerformed(evt);
            }
        });
        mnuPizzas.add(mnuNovaPizza);
        mnuPizzas.add(jSeparator3);

        mnuPesquisarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/magnifying-glass11.png"))); // NOI18N
        mnuPesquisarPizza.setText("Pesquisar");
        mnuPesquisarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisarPizzaActionPerformed(evt);
            }
        });
        mnuPizzas.add(mnuPesquisarPizza);

        mnuTelaPrincipal.add(mnuPizzas);
        mnuPizzas.getAccessibleContext().setAccessibleName("");

        mnuPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/pencil41.png"))); // NOI18N
        mnuPedidos.setText("Pedidos");
        mnuPedidos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuPedidos.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuPedidos.setVerifyInputWhenFocusTarget(false);

        mnuNovoPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/archive44.png"))); // NOI18N
        mnuNovoPedido.setText("Novo");
        mnuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuNovoPedido);
        mnuPedidos.add(jSeparator4);

        mnuPesquisarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/magnifying-glass11.png"))); // NOI18N
        mnuPesquisarPedido.setText("Pesquisar");
        mnuPesquisarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisarPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuPesquisarPedido);

        mnuTelaPrincipal.add(mnuPedidos);
        mnuPedidos.getAccessibleContext().setAccessibleName("");

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/office-worker2.png"))); // NOI18N
        mnuUsuarios.setText("Usuários");
        mnuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuUsuarios.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuUsuarios.setVerifyInputWhenFocusTarget(false);

        mnuNovoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/profile3.png"))); // NOI18N
        mnuNovoUsuario.setText("Novo");
        mnuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuNovoUsuario);
        mnuUsuarios.add(jSeparator6);

        mnuPesquisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/magnifying-glass11.png"))); // NOI18N
        mnuPesquisarUsuario.setText("Pesquisar");
        mnuPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisarUsuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuPesquisarUsuario);

        mnuTelaPrincipal.add(mnuUsuarios);
        mnuUsuarios.getAccessibleContext().setAccessibleName("");

        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuRelatorios.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuRelatorios.setVerifyInputWhenFocusTarget(false);
        mnuTelaPrincipal.add(mnuRelatorios);
        mnuRelatorios.getAccessibleContext().setAccessibleName("");

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/question58.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuAjuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuAjuda.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuAjuda.setVerifyInputWhenFocusTarget(false);
        mnuTelaPrincipal.add(mnuAjuda);
        mnuAjuda.getAccessibleContext().setAccessibleName("");

        mnuUsuariLogadoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/profile27.png"))); // NOI18N
        mnuUsuariLogadoSistema.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mnuUsuariLogadoSistema.setHideActionText(true);
        mnuUsuariLogadoSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuUsuariLogadoSistema.setMargin(new java.awt.Insets(2, 20, 2, 10));
        mnuUsuariLogadoSistema.setVerifyInputWhenFocusTarget(false);

        mnuMudarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/tool826.png"))); // NOI18N
        mnuMudarSenha.setText("Alterar senha");
        mnuUsuariLogadoSistema.add(mnuMudarSenha);
        mnuUsuariLogadoSistema.add(jSeparator5);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gestao/pizzaria/icones/logout15.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        mnuUsuariLogadoSistema.add(jMenuItem1);

        mnuTelaPrincipal.add(mnuUsuariLogadoSistema);

        setJMenuBar(mnuTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoClienteActionPerformed
        this.exibirTelaCadastroCliente();
    }//GEN-LAST:event_mnuNovoClienteActionPerformed

    private void mnuPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisarClienteActionPerformed
        this.exibirTelaPesquisaCliente();
    }//GEN-LAST:event_mnuPesquisarClienteActionPerformed

    private void mnuNovaBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaBebidaActionPerformed
        this.exibirTelaCadastroBebida();
    }//GEN-LAST:event_mnuNovaBebidaActionPerformed

    private void mnuPesquisarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisarBebidaActionPerformed
        this.exibirTelaPesquisaBebida();
    }//GEN-LAST:event_mnuPesquisarBebidaActionPerformed

    private void mnuNovaPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaPizzaActionPerformed
        this.exibirTelaCadastroPizza();
    }//GEN-LAST:event_mnuNovaPizzaActionPerformed

    private void mnuPesquisarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisarPizzaActionPerformed
        this.exibirTelaPesquisaPizza();
    }//GEN-LAST:event_mnuPesquisarPizzaActionPerformed

    private void mnuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoPedidoActionPerformed
        this.exibirTelaCadastroPedido();
    }//GEN-LAST:event_mnuNovoPedidoActionPerformed

    private void mnuPesquisarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisarPedidoActionPerformed
        this.exibirTelaPesquisaPedido();
    }//GEN-LAST:event_mnuPesquisarPedidoActionPerformed

    private void mnuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoUsuarioActionPerformed
        this.exibirTelaCadastroUsuario();
    }//GEN-LAST:event_mnuNovoUsuarioActionPerformed

    private void mnuPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisarUsuarioActionPerformed
        this.exibirTelaPesquisaUsuario();
    }//GEN-LAST:event_mnuPesquisarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialSistema().setVisible(true);
            }
        });
    }

    private void exibirTelaPesquisaBebida() {
        if (pesquisarBebidaForm == null) {
            pesquisarBebidaForm = new PesquisarBebidaForm();
        }
        pesquisarBebidaForm.setVisible(true);
        pesquisarBebidaForm.toFront();
    }
    
    private void exibirTelaCadastroBebida() {
        if (cadastrarBebidaForm == null) {
            cadastrarBebidaForm = new CadastrarBebidaForm();
        }
        cadastrarBebidaForm.setVisible(true);
        cadastrarBebidaForm.toFront();
    }

    private void exibirTelaPesquisaUsuario() {
        if (pesquisarUsuarioForm == null) {
            pesquisarUsuarioForm = new PesquisarUsuarioForm();
        }
        pesquisarUsuarioForm.setVisible(true);
        pesquisarUsuarioForm.toFront();
    }
    
    private void exibirTelaCadastroUsuario() {
        if (cadastrarUsuarioForm == null) {
            cadastrarUsuarioForm = new CadastrarUsuarioForm();
        }
        cadastrarUsuarioForm.setVisible(true);
        cadastrarUsuarioForm.toFront();
    }
    
    private void exibirTelaPesquisaPizza() {
        if (pesquisarPizzaForm == null) {
            pesquisarPizzaForm = new PesquisarPizzaForm();
        }
        pesquisarPizzaForm.setVisible(true);
        pesquisarPizzaForm.toFront();        
    }
    
    private void exibirTelaCadastroPizza() {
        if (cadastrarPizzaForm == null) {
            cadastrarPizzaForm = new CadastrarPizzaForm();
        }
        cadastrarPizzaForm.setVisible(true);
        cadastrarPizzaForm.toFront();
    }
    
    private void exibirTelaPesquisaCliente() {
        if (pesquisarClienteForm == null) {
            pesquisarClienteForm = new PesquisarClienteForm();
        }
        pesquisarClienteForm.setVisible(true);
        pesquisarClienteForm.toFront();
    }
    
    private void exibirTelaCadastroCliente() {
        if (cadastrarClienteForm == null) {
            cadastrarClienteForm = new CadastrarClienteForm();
        }
        cadastrarClienteForm.setVisible(true);
        cadastrarClienteForm.toFront();
    }
    
    private void exibirTelaPesquisaPedido() {
        if (pesquisarPedidoForm == null) {
            pesquisarPedidoForm = new PesquisarPedidoForm();
        }
        pesquisarPedidoForm.setVisible(true);
        pesquisarPedidoForm.toFront();
    }
    
    private void exibirTelaCadastroPedido() {
        if (cadastrarPedidoForm == null) {
            cadastrarPedidoForm = new CadastrarPedidoForm();
        }
        cadastrarPedidoForm.setVisible(true);
        cadastrarPedidoForm.toFront();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuBebidas;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuMudarSenha;
    private javax.swing.JMenuItem mnuNovaBebida;
    private javax.swing.JMenuItem mnuNovaPizza;
    private javax.swing.JMenuItem mnuNovoCliente;
    private javax.swing.JMenuItem mnuNovoPedido;
    private javax.swing.JMenuItem mnuNovoUsuario;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenuItem mnuPesquisarBebida;
    private javax.swing.JMenuItem mnuPesquisarCliente;
    private javax.swing.JMenuItem mnuPesquisarPedido;
    private javax.swing.JMenuItem mnuPesquisarPizza;
    private javax.swing.JMenuItem mnuPesquisarUsuario;
    private javax.swing.JMenu mnuPizzas;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenuBar mnuTelaPrincipal;
    private javax.swing.JMenu mnuUsuariLogadoSistema;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
