/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestao.pizzaria.apresentacao;

/**
 *
 * @author melot_000
 */
public class TelaInicialSistema extends javax.swing.JFrame {

    PesquisarBebidaForm pesquisarBebidaForm;
    PesquisarUsuarioForm pesquisarUsuarioForm;
    PesquisarPizzaForm pesquisarPizzaForm;

    /**
     * Creates new form TelaInicialSistema
     */
    public TelaInicialSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastrar = new javax.swing.JMenu();
        mnuCadastrarCliente = new javax.swing.JMenuItem();
        mnuCadastrarBebidas = new javax.swing.JMenuItem();
        mnuCadastrarPedidos = new javax.swing.JMenuItem();
        mnuCadastrarPizza = new javax.swing.JMenuItem();
        mnuCadastrarUsuario = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestão Pizzaria");
        setExtendedState(6);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 5, 0, 0));

        mnuCadastrar.setText("Cadastrar");
        mnuCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        mnuCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuCadastrarCliente.setText("Clientes");
        mnuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarClienteActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarCliente);

        mnuCadastrarBebidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuCadastrarBebidas.setText("Bebidas");
        mnuCadastrarBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarBebidasActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarBebidas);

        mnuCadastrarPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuCadastrarPedidos.setText("Pedidos");
        mnuCadastrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarPedidosActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarPedidos);

        mnuCadastrarPizza.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK));
        mnuCadastrarPizza.setText("Pizzas");
        mnuCadastrarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarPizzaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadastrarPizza);

        mnuCadastrarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuCadastrarUsuario.setText("Usuarios");
        mnuCadastrar.add(mnuCadastrarUsuario);

        jMenuBar1.add(mnuCadastrar);

        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jMenuBar1.add(mnuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarBebidasActionPerformed
        this.exibirTelaPesquisaBebida();
    }//GEN-LAST:event_mnuCadastrarBebidasActionPerformed

    private void mnuCadastrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrarPedidosActionPerformed

    private void mnuCadastrarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarPizzaActionPerformed
        this.exibirTelaPesquisaPizza();
    }//GEN-LAST:event_mnuCadastrarPizzaActionPerformed

    private void mnuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuCadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialSistema().setVisible(true);
            }
        });
    }

    private void exibirTelaPesquisaBebida() {
        if (pesquisarBebidaForm == null) {
            pesquisarBebidaForm = new PesquisarBebidaForm();
        }
        pesquisarBebidaForm.setVisible(true);
        pesquisarBebidaForm.toFront();
    }

    private void exibirTelaPesquisaUsuario() {
        if (pesquisarUsuarioForm == null) {
            pesquisarUsuarioForm = new PesquisarUsuarioForm();
        }
        pesquisarUsuarioForm.setVisible(true);
        pesquisarUsuarioForm.toFront();
    }
    
    private void exibirTelaPesquisaPizza() {
        if (pesquisarPizzaForm == null) {
            pesquisarPizzaForm = new PesquisarPizzaForm();
        }
        pesquisarPizzaForm.setVisible(true);
        pesquisarPizzaForm.toFront();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenuItem mnuCadastrarBebidas;
    private javax.swing.JMenuItem mnuCadastrarCliente;
    private javax.swing.JMenuItem mnuCadastrarPedidos;
    private javax.swing.JMenuItem mnuCadastrarPizza;
    private javax.swing.JMenuItem mnuCadastrarUsuario;
    private javax.swing.JMenu mnuRelatorios;
    // End of variables declaration//GEN-END:variables
}
